[package]
name = "qualia"
version = "0.0.1"
authors = ["Wojciech Kluczka <wojciech.kluczka@gmail.com>"]

[dependencies]
dbus = "0.3.4"
libc = "0.2.16"
libudev = "0.2.0"
nix = "0.6.0"
time = "0.1"
xkbcommon = "0.2"
timber = { path = "../timber" }
dharma = { path = "../dharma" }

[lib]
name = "qualia"
path = "lib.rs"

