[package]
name = "frames"
version = "0.0.1"
authors = ["Wojciech Kluczka <wojciech.kluczka@gmail.com>"]

[dependencies]
timber = { path = "../timber" }
qualia = { path = "../qualia" }

[lib]
name = "frames"
path = "lib.rs"

