[package]
name = "coordination"
version = "0.0.1"
authors = ["Wojciech Kluczka <wojciech.kluczka@gmail.com>"]

[dependencies]
timber = { path = "../timber" }
dharma = { path = "../dharma" }
qualia = { path = "../qualia" }

[lib]
name = "coordination"
path = "lib.rs"

