[workspace]

members = [
        "src/dharma",
        "src/qualia",
        "src/frames",
        "src/exhibitor",
        "src/device_manager",
        "src/wayland_frontend",
        "src/perceptia",
        "src/perceptiactl"
    ]

