[workspace]

members = [
        "src/dharma",
        "src/timber",
        "src/skylane",
        "src/skylane_scanner",
        "src/skylane_protocols",
        "src/qualia",
        "src/frames",
        "src/renderer_gl",
        "src/output",
        "src/device_manager",
        "src/exhibitor",
        "src/wayland_frontend",
        "src/perceptia",
        "src/perceptiactl",
    ]

