[package]
name = "perceptiactl"
version = "0.0.1"
authors = ["Wojciech Kluczka <wojciech.kluczka@gmail.com>"]

[dependencies]
clap = "2.11.3"
timber         = { path = "../timber" }
device_manager = { path = "../device_manager" }

[[bin]]
name = "perceptiactl"
path = "perceptiactl.rs"

