[package]
name = "device_manager"
version = "0.0.1"
authors = ["Wojciech Kluczka <wojciech.kluczka@gmail.com>"]

[dependencies]
dharma = { path = "../dharma" }
qualia = { path = "../qualia" }

[lib]
name = "device_manager"
path = "lib.rs"

