[package]
name = "skylane_scanner"
version = "0.0.1"
authors = ["Wojciech Kluczka <wojciech.kluczka@gmail.com>"]

[dependencies]
xml-rs = "0.3"

[lib]
name = "skylane_scanner"
path = "lib.rs"

[[bin]]
name = "skylane_scanner"
path = "bin.rs"

