[package]
name = "wayland_frontend"
version = "0.0.1"
authors = ["Wojciech Kluczka <wojciech.kluczka@gmail.com>"]
build = "build.rs"

[build-dependencies]
gcc = "0.3"

[dependencies]
libc = "0.2.15"
timber = { path = "../timber" }
qualia = { path = "../qualia" }

[lib]
name = "wayland_frontend"
path = "lib.rs"

