[package]
name = "wayland_frontend"
version = "0.0.1"
authors = ["Wojciech Kluczka <wojciech.kluczka@gmail.com>"]

[dependencies]
nix = "0.8.0"
timber = { path = "../timber" }
dharma = { path = "../dharma" }
qualia = { path = "../qualia" }
skylane = { path = "../skylane" }
skylane_protocols = { path = "../skylane_protocols" }

[lib]
name = "wayland_frontend"
path = "lib.rs"

