[package]
name = "wayland_frontend"
version = "0.0.1"
authors = ["Wojciech Kluczka <wojciech.kluczka@gmail.com>"]

[dependencies]
nix = "0.8.0"
skylane = "0.1.0"
skylane_protocols = "0.1.0"
timber = { path = "../timber" }
dharma = { path = "../dharma" }
qualia = { path = "../qualia" }
coordination = { path = "../coordination" }

[lib]
name = "wayland_frontend"
path = "lib.rs"

