[package]
name = "exhibitor"
version = "0.0.1"
authors = ["Wojciech Kluczka <wojciech.kluczka@gmail.com>"]

[dependencies]
qualia = { path = "../qualia" }

[lib]
name = "exhibitor"
path = "exhibitor.rs"

