[package]
name = "renderer_gl"
version = "0.0.1"
authors = ["Wojciech Kluczka <wojciech.kluczka@gmail.com>"]

[dependencies]
egl = "0.2.6"
gl = "0.6.0"
timber = { path = "../timber" }
qualia = { path = "../qualia" }

[lib]
name = "renderer_gl"
path = "lib.rs"

